version: "3.1"
# https://docs.docker.com/compose/compose-file/

services:

  mysql:
    image: mysql:5.7.18
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8mb4_unicode_ci' --init-connect='SET NAMES utf8mb4;' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower-case-table-names=2 --max-connections=500
    container_name: coderslab_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=coderslab
    ports:
     - "3306:3306"
    volumes:
      - ./config:/etc/mysql/conf.d
      - coderslab_mysql_data:/var/lib/mysql

volumes:
  coderslab_mysql_data:
